protected/models/AdminItems_form.php
<?php
class AdminItems_form extends CFormModel{
	public $kind;
	public $city;
	public $status;
	public $owner;

	public function rules(){
	return array(
		array('city', 'match', 'pattern' => '/^[ёа-я0-9. \/-]+$/ui', 'message' => '{attribute} содержит недопустимые символы.'),
		array('kind, status, owner', 'numerical', 'integerOnly'=>true),
		array('city, kind, status, owner', 'safe')
		);
	}


	public function attributeLabels(){
		return array(
			'kind'		=>'Помещение',
			'city'		=>'Город',
			'status'	=>'Статус',
			'owner'		=>'Владелец'
		);
	}

	}
?>

protected/controllers/AdminitemsController.php
<?php
class AdminitemsController extends CController{
	public $defaultAction = 'view';
	public $layout = 'control';
	public $pageDescription;
	public $pageKeywords;

	public function actionView(){
		$this->pageTitle = 'Управление объектами';
		$this->pageDescription = '';
		$this->pageKeywords = '';
		$usr = Yii::app()->user;
		$form = new AdminItems_form();
		if (isset($_POST['AdminItems_form']) || (count($_POST)>0)){
			$form->attributes = $_POST['AdminItems_form'];
			if ($form->validate()){
				if ((isset($_POST['AdminItems_form']['city'])) && (!is_numeric($_POST['AdminItems_form']['city'])))
					$usr->setState('aicity', $_POST['AdminItems_form']['city']);
				elseif (isset($usr->aicity))	unset ($usr->aicity);
				if ((isset($_POST['AdminItems_form']['owner'])) && ($_POST['AdminItems_form']['owner']!=0)) // Владелей объекта
					$usr->setState('aiowner', $_POST['AdminItems_form']['owner']);
				elseif (isset($usr->aiowner))	unset ($usr->aiowner);
				if ((isset($_POST['AdminItems_form']['status'])) && ($_POST['AdminItems_form']['status']!=90)) // Статус объекта
					$usr->setState('aistatus', $_POST['AdminItems_form']['status']);
				elseif (isset($usr->aistatus))	unset ($usr->aistatus);
				if ((isset($_POST['AdminItems_form']['kind'])) && ($_POST['AdminItems_form']['kind']!=90)) // Тип помещения
					$usr->setState('aikind', $_POST['AdminItems_form']['kind']);
				elseif (isset($usr->aikind))	unset ($usr->aikind);
			}
		}

		$whereString = ''; // Переменная для формирования WHERE-предложения sql-запроса
		$Params = array(); // Массив параметров, передаваемых в запрос
		if (isset($usr->aicity)) {
			$whereString .= ' and I.city=:ct';
			$Params[':ct'] = $usr->getState('aicity', '');
		}
		if (isset($usr->aikind)) {
			$whereString .= ' and I.kind=:kd';
			$Params[':kd'] = $usr->getState('aikind', 0);
		}
		if (isset($usr->aistatus)) {
			$whereString .= ' and I.status=:st';
			$Params[':st'] = $usr->getState('aistatus', 0);
		}
		if (isset($usr->aiowner)) {
			$whereString .= ' and I.owner_id=:wn';
			$Params[':wn'] = $usr->getState('aiowner', 0);
		}
		if ($whereString!='')	$whereString = substr($whereString, 5);

        # Определяем сортировку для запроса, если нет сортировки то сортируем по id обекта
        $order = '';
		if (isset($_GET['sort'])){		  $order = $_GET['sort'];
		  if (isset($_GET['type'])) $order .= ' desc';		}
		if (empty($order)) $order = 'id';

		$criteria = new CDbCriteria;
		$criteria->alias = 'I';
		$criteria->select = 'I.id, I.created, I.status, I.itemType, I.special, I.parent, (Select COALESCE(MAX(C.id), 0) from items C where C.parent=I.id) as "hasChild", I.kind, I.city, D.name as "district", S.name as "street", COALESCE(I.house, "?") as house, COALESCE(I.housing, "?") as housing, I.owner_id, U.username as "login", U.so_name as "lastname", U.name as "firstname", (Select COUNT(*) from item_show_stat SS where SS.item=I.id) as "showQty"';
		$criteria->join = 'left join streets S on S.id=I.street left join districts D on D.id=I.district left join users U on U.id=I.owner_id';
		$criteria->condition = $whereString;
		$criteria->params = $Params;
		$criteria->order = $order;

		$qty = Search::model()->count($criteria);
		# Постраничная разбивка
		$pages = new CPagination($qty);
		$pages->pageSize = 10;
		$pages->applyLimit($criteria);
		# Получаем текущую страницу (нумерация начинается с 0, поэтому +1)
		$Cpage = $pages->getCurrentPage()+1;

		$Items = Search::model()->findAll($criteria);

		$criteria = new CDbCriteria;
		$criteria->order = 'name';
		$arCities = CHtml::listData( City::model()->findAll($criteria), 'name', 'name');
		array_unshift($arCities, 'Любой');

		$criteria = new CDbCriteria;
		$criteria->select = 'id, username, so_name';
		$criteria->condition = 'role=:r';
		$criteria->params = array(':r'=>'owner');
		$criteria->order = 'username';
		$Rows = User::model()->findAll($criteria);
		$arUsers[0] = 'Любой';
		if (!empty($Rows))
			foreach ($Rows as $user)
				$arUsers[$user->id] = $user->username.' ('.$user->so_name.')';

		$arStatus = array(90=>'Любой', 0=>'деактивирован', 3=>'на модерации', 6=>'идут показы');
		$arKinds = array(90=>'Любое', 0=>'офис', 1=>'торговое', 2=>'Склад\Производство');

		$this->render('view', array(
			'form'		=>$form,
			'rows'		=>$Items,
			'pages'		=>$pages,
			'foundQty'	=>$qty,
			'Cities'	=>$arCities,
			'city'		=>$usr->getState('aicity', 0),
			'Kinds'		=>$arKinds,
			'kind'		=>$usr->getState('aikind', 90),
			'Statuses'	=>$arStatus,
			'status'	=>$usr->getState('aistatus', 90),
			'Users'		=>$arUsers,
			'owner'		=>$usr->getState('aiowner', 0),
			'Cpage'		=>$Cpage
			));
	}
	public function actionDelete(){
		$get = $this->widget('GetChek', array('get_mass'=>$_GET));
		$id = $get->id_out;

		if (isset($_GET['flg'])){
			$Row = Search::model()->findByPK($id);
			if (empty($Row))
				throw new CHttpException(404);

			// Удалим статистику показов объекта
			$cmd = Yii::app()->db->createCommand('Delete from item_show_stat where item='.$Row->id.';');
			$cmd->execute();
			// Удалим объект из блокнтов арендаторов
			$cmd = Yii::app()->db->createCommand('Delete from notepad where item='.$Row->id.';');
			$cmd->execute();
			$s = Yii::app()->params->web_root;
			$i = strrpos($s, '/'); $a = strlen($s)-1;
			if ($i != $a)	$s.='/';
			// Удалим фотографии объекта
			$Fotos = Images::model()->findAll('id_item=:ii', array(':ii'=>$id));
			if (!empty($Fotos)) {
				$p = $s.'storage/images/';
				foreach ($Fotos as $foto) {
					@unlink ($p.$foto->img);
					@unlink ($p.'_thumbs/'.$foto->name_medium);
					@unlink ($p.'_thumbs/'.$foto->name_small);
				}
				$cmd = Yii::app()->db->createCommand('Delete from images where id_item='.$Row->id.';');
				$cmd->execute();
			}
			// Удалим прикрепленные файлы
			$Attachs = Attach::model()->findAll('item=:ii', array(':ii'=>$Row->id));
			if (!empty($Attachs)) {
				$p = $s.'storage/files/objs/';
				foreach ($Attachs as $fl)
					@unlink ($p.$fl->filename);
				$cmd = Yii::app()->db->createCommand('Delete from attachs where item='.$Row->id.';');
				$cmd->execute();
			}
			// Удалим (если есть) файл-архив с описанием объекта
			$p = $s.'storage/files/zipobj/obj'.$Row->id.'.zip';
			if (file_exists($p))
				@unlink ($p);
			// Удалим (если есть) pdf-файл с описанием объекта
			$p = $s.'storage/files/pdfobj/obj'.$Row->id.'.pdf';
			if (file_exists($p))
				@unlink ($p);

			if ($Objects_del->delete(false))
				$this->redirect(array('owner/view'));

			$Row->delete(false);
			$this->redirect(array('adminitems/view'));
		}

		$this->render('delete', array('id'=>$id));
	}

	public function actionUnset(){
		$usr = Yii::app()->user;
		unset($usr->aicity);
		unset($usr->aikind);
		unset($usr->aistatus);
		unset($usr->aiowner);
		$this->redirect(array('adminitems/view'));
	}

	public function filters(){
	return array(
		array(
			'application.filters.AccessFilter',
			'role'=>'admin',
		)
	);
	}
}
?>

protected/views/adminitems/_row.php
<?php switch ($obj->kind) {
	case 1 : {$type = 'торговое'; break;}
	case 2 : {$type = 'склад\произв'; break;}
	default : $type = 'офис'; 
}
switch ($obj->status) {
	case 0 : {$status='деактивирован'; break;}
	case 1 : {$status = 'отменен'; break;}
	//case 2 : {$status = 'сдан'; break;}
	case 3 : {$status='на модерации'; break;}
	//case 5 : {$status = 'приостановлен'; break;}
	case 6 : {$status='идут показы'; break;}
	default: {$status = 'Не известен'; }
}
switch ($obj->itemType) {
	case 1 : {$iType='центр'; break;}
	case 2 : {$iType=CHtml::link('помещение', array('control/obj_detail', 'id'=>$obj->parent)); break;}
	default: {$iType='обычный'; }
}
?>
<tr>
	<td><?php $get = $this->widget('DateFormat', array('kind'=>5,'dbDate'=>$obj->created)); echo $get->date; ?></td>
	<td><?php echo CHtml::link('<span id="'.$obj->id.'">'.$status.'</span>', array('#'), array('class'=>'change')); ?><br /><?php echo CHtml::link('Спец', array('#'), array('class'=>'chspec', 'id'=>'ln'.$obj->id)); ?>: <span id="sp<?php echo $obj->id?>"><?php echo $obj->special?'ДА':'НЕТ';?></span></td>
	<td><?php echo $iType; ?></td>
	<td><?php echo $type; ?></td>
	<td><?php if (isset($obj->login)) echo CHtml::link($obj->login.' ('.$obj->firstname.' '.$obj->lastname.')', array('adminusers/detail', 'id'=>$obj->owner_id)); else echo 'Аноним'; ?></td>
	<td><?php echo CHtml::link($obj->city.': '.$obj->district.' / '.$obj->street.', '.$obj->house.'('.$obj->housing.')', array('control/obj_detail', 'id'=>$obj->id)); ?></td>
	<td><?php echo $obj->showQty; ?></td>
	<td class="action"><?php echo CHtml::link('D', array('adminitems/delete', 'id'=>$obj->id)); ?></td>
</tr>

protected/views/adminitems/delete.php
Вы уверенны, что хотите удалить выбранный Объект?<br /><br />
<?php echo CHtml::link('Да', array('adminitems/delete', 'id'=>$id, 'flg'=>'chek')); ?> <?php echo CHtml::link('Нет', array('adminitems/view')); ?>

protected/views/adminitems/view.php
<?php echo CHtml::cssFile(Yii::app()->baseUrl.'/css/form.css'); ?>
Фильтры: <?php echo CHtml::link('Сбросить', array('adminitems/unset')); ?><br />
<div class="form">
	<?php echo CHtml::form(); ?>
	<?php echo CHtml::errorSummary($form, 'Исправьте, пожалуйста, следующие ошибки:'); ?>
	<strong><?php echo CHtml::activeLabel($form, 'city'); ?>:</strong> <?php echo CHtml::dropDownList('AdminItems_form[city]', $city, $Cities); ?>
	<strong><?php echo CHtml::activeLabel($form, 'kind'); ?>:</strong> <?php echo CHtml::dropDownList('AdminItems_form[kind]', $kind, $Kinds); ?>
	<strong><?php echo CHtml::activeLabel($form, 'status'); ?>:</strong> <?php echo CHtml::dropDownList('AdminItems_form[status]', $status, $Statuses); ?>
	<strong><?php echo CHtml::activeLabel($form, 'owner'); ?>:</strong> <?php echo CHtml::dropDownList('AdminItems_form[owner]', $owner, $Users); ?>
	<div class="row buttons">
		<br /><?php echo CHtml::submitButton('Найти', array('id'=>'submit')); ?><br />
	</div>
	<?php echo CHtml::endForm(); ?>
</div><!--form-->
<?php if (is_array($rows)):?>
<hr>Найдено объектов: <?php echo $foundQty; ?><br /><br />
<?php if (!empty($rows)):?>
<style type="text/css">
table.sample {
  border-spacing: 2px;
  border-collapse: collapse;
  width: 100%;
  text-align: left;
}
table.sample th {
  border: 1px solid #000000;
  padding: 5px;
  background-color: #aaaaaa;
  text-align: center;
}
table.sample td {
  border: 1px solid #000000;
  padding: 5px;
}
table.sample td.action {
  text-align: center;
}
</style>
<script type="text/javascript" src="js/jquery.simplemodal.js"></script>
<script type="text/javascript" src="js/adminitems.js"></script>
<?php echo CHtml::cssFile(Yii::app()->baseUrl.'/css/modal.css'); ?>
<div id="mwindow">
	<div class="header"></div>
	<div class="message">
		<input type="radio" name="stat" value="0" alt="деактивирован" id="rb0" /><label for="rb0">заблокировать</label><br />
		<input type="radio" name="stat" value="1" alt="приостановлен" id="rb2" /><label for="rb2">остановить показы</label><br />
		<input type="radio" name="stat" value="6" alt="идут показы" id="rb3" /><label for="rb3">возобновить показы</label>
	</div>
	<div class="buttons">
		<div class="yes">Сохранить</div><div class="no close">Отмена</div>
	</div>
</div>
<div id="admin-allow">
	<div class="header"></div>
	<div class="message">
		<input type="radio" name="spec" value="0" alt="НЕТ" id="rbs0" /><label for="rbs0">снять</label><br />
		<input type="radio" name="spec" value="1" alt="ДА" id="rbs1" /><label for="rbs1">установить</label><br />
	</div>
	<div class="buttons">
		<div class="yes">Сохранить</div><div class="no close">Отмена</div>
	</div>
</div>
<?php echo CHtml::link('Сбросить сортировку', array('adminitems/view', 'page'=>$Cpage)); ?>
<table class="sample">
	<tr>
		<th>Создан <?php echo CHtml::link('&uarr;', array('adminitems/view', 'page'=>$Cpage, 'sort'=>'created')); ?>&nbsp;<?php echo CHtml::link('&darr;', array('adminitems/view', 'page'=>$Cpage, 'sort'=>'created', 'type'=>'desc')); ?>
		</th>
		<th>Статус <?php echo CHtml::link('&uarr;', array('adminitems/view', 'page'=>$Cpage, 'sort'=>'status')); ?>&nbsp;<?php echo CHtml::link('&darr;', array('adminitems/view', 'page'=>$Cpage, 'sort'=>'status', 'type'=>'desc')); ?>
		</th>
		<th>Объект</th>
		<th>Тип помещ. <?php echo CHtml::link('&uarr;', array('adminitems/view', 'page'=>$Cpage, 'sort'=>'kind')); ?>&nbsp;<?php echo CHtml::link('&darr;', array('adminitems/view', 'page'=>$Cpage, 'sort'=>'kind', 'type'=>'desc')); ?>
		</th>
		<th>Владелец <?php echo CHtml::link('&uarr;', array('adminitems/view', 'page'=>$Cpage, 'sort'=>'login')); ?>&nbsp;<?php echo CHtml::link('&darr;', array('adminitems/view', 'page'=>$Cpage, 'sort'=>'login', 'type'=>'desc')); ?>
		</th>
		<th>Адрес</th>
		<th>Показы</th>
		<th>Уд.</th>
	</tr>
<?php
		foreach ($rows as $row)
			$this->renderPartial('_row', array('obj' =>$row));
?>
<?php endif; ?>
</table>
<div align="center">
<?php
  $this->widget('CLinkPager',array(
		'pages'          =>$pages,
		'maxButtonCount' =>5, # максимальное колличество вкладок на странице
		'header'         =>'<b>Перейти к странице:</b><br>', # заголовок
		'nextPageLabel'  =>'Вперед&gt;', # название кнопок навигаций next и prev
		'prevPageLabel'  =>'&lt;Назад',
  ));
?>
</div>
<?php endif; ?>