protected/models/SendOrder.php
<?php class SendOrder extends CFormModel{

	public $name;
	public $phone;
	public $e_mail;
	public $verifyCode;

	public $kind;
	public $about;
	public $city;
	public $district;
	public $street;
	public $house;
	public $housing;
	public $stage;
	public $staging;
	public $square;
	public $price;
	public $fotos;

	public function rules(){
		return array(
			array('name, e_mail, phone, kind, about, city, district, street, house, housing, stage, staging, square, price', 'safe'),
			array('city, district, street, name, phone, e_mail', 'required', 'message'=>'Обязательно укажите {attribute}.'),
			array('e_mail', 'email', 'message'=>'{attribute} имеет недопустимый формат.'),
			array('verifyCode', 'captcha', 'allowEmpty'=>!extension_loaded('gd'), 'message'=>'Код с картинки введен неверно.')
		);
	}

	public function attributeLabels(){
		return array(
			'city'		=>'Город',
			'district'	=>'Район',
			'street'	=>'Улица',
			'name'		=>'Имя',
			'e_mail'	=>'E-mail',
			'phone'		=>'Контактный телефон'
		);
	}

}?>

protected/controllers/SendorderController.php
<?php 
class SendorderController extends CController{

	public $defaultAction = 'view';
	public $layout = 'inner02';
	public $pageDescription;
	public $pageKeywords;
	public $jsFiles = array('new.js');
	public $toBodyTag = ' onload="fakeUploads();"';

	public function actions(){
		return array(
			'captcha'=>array(
				'class'=>'MyCCaptchaAction',
				/*'class'=>'CCaptchaAction',
				'backColor'=> 0x003300,
				'maxLength'=> 3,
				'minLength'=> 3,
				'foreColor'=> 0x66FF66,*/
			),
		);
	}

	public function actionView(){

		$form = new SendOrder();
		$wasSend = false;
		$kind = 0; $about = '';
		
		if (!empty($_POST['SendOrder'])){
			ini_set('memory_limit', '72M');
			ini_set('upload_max_filesize', '9M');
			$form->attributes = $_POST['SendOrder'];
			$kind = $form->kind;
			$about = $form->about;
			if ($form->validate()){
				$filter = new CHtmlPurifier();
				$form->e_mail = $filter->purify($form->e_mail);
				$form->name = $filter->purify($form->name);
				$form->phone = $filter->purify($form->phone);

				$form->about = $filter->purify($form->about);
				$form->city = $filter->purify($form->city);
				$form->district = $filter->purify($form->district);
				$form->street = $filter->purify($form->street);
				$form->house = $filter->purify($form->house);
				$form->housing = $filter->purify($form->housing);
				$form->stage = $filter->purify($form->stage);
				$form->staging = $filter->purify($form->staging);
				$form->square = $filter->purify($form->square);
				$form->price = $filter->purify($form->price);

				$form->fotos[] = CUploadedFile::getInstance($form,'[1]fotos');
				$form->fotos[] = CUploadedFile::getInstance($form,'[2]fotos');
				$form->fotos[] = CUploadedFile::getInstance($form,'[3]fotos');
				$form->fotos[] = CUploadedFile::getInstance($form,'[4]fotos');
				$form->fotos[] = CUploadedFile::getInstance($form,'[5]fotos');

				// Отсылаем письмо
				require_once('protected/extensions/mailer/class.mailer.php');
				$mail = new Mailer();
				$mail->From = Yii::app()->params->admin_mail;
				$mail->Subject  = 'Заявка на размещение объекта';
				$Flds[0] = 'Город : '; if (empty($form->city)) $Flds[0].='?'; else $Flds[0] .= $form->city; $Flds[0].="\n";
				$Flds[1] = 'Район : '; if (empty($form->district)) $Flds[1].='?'; else $Flds[1] .= $form->district; $Flds[1].="\n";
				$Flds[2] = 'Улица : '; if (empty($form->street)) $Flds[2].='?'; else $Flds[2] .= $form->street; $Flds[2].="\n";
				$Flds[3] = 'Дом : '; if (empty($form->house)) $Flds[3].='?'; else $Flds[3] .= $form->house; $Flds[3].="\n";
				$Flds[4] = 'Дом : '; if (empty($form->housing)) $Flds[4].='?'; else $Flds[4] .= $form->housing; $Flds[4].="\n";
				$Flds[5] = 'Этаж : '; if (empty($form->stage)) $Flds[5].='?'; else $Flds[5] .= $form->stage; $Flds[5].="\n";
				$Flds[6] = 'Этажность : '; if (empty($form->staging)) $Flds[6].='?'; else $Flds[6] .= $form->staging; $Flds[6].="\n";
				$Flds[7] = 'Площадь : '; if (empty($form->square)) $Flds[7].='?'; else $Flds[7] .= $form->square; $Flds[7].="\n";
				$Flds[8] = 'Цена : '; if (empty($form->price)) $Flds[8].='?'; else $Flds[8] .= $form->price; $Flds[8].="\n";
				$Flds[9] = 'Дополнительно : '; if (empty($form->about)) $Flds[9].='?'; else $Flds[9] .= $form->about; $Flds[9].="\n";
				$txt = 'Тип объекта: ';
				switch ($form->kind){
					case 1: {$txt.='Торговое помещение'; break;}
					case 2: {$txt.='Склад/Производство'; break;}
					default: $txt.='Офис';
				}
				$txt.="\n";
				for ($i=0;$i<10;$i++)
					$txt.= $Flds[$i];
				$mail->Body = 'Имя отправителя: '.$form->name."\n".'Обратный email: '.$form->e_mail."\n".'Контактный телефон: '.$form->phone."\n".'Время подачи заявки: '.date('d.m.Y h:i:s')."\n\n".'Значения полей --'."\n".$txt;
				// Фото
				$Attachs = array();
				if (!empty($form->fotos)){
					foreach ($form->fotos as $file)
						if (!empty($file) && file_exists($file->tempName)) {
							$translit = $this->widget('LoadFileName', array('in_text'=>$file->name, 'len'=>200));
							$fname = 'storage/images/mail_attachs/'.$translit->out_text;
							if ($file->saveAs($fname)){
								$Attachs[] = $fname;
								$mail->AddAttachment ($fname, $file->name);
							}
						}
				}
			   $mail->AddAddress('office@com-arenda.ru');
				if ($mail->Send())
					$wasSend = true;
				// Удалим временно сохраненные файлы, прикрепленные к письму
				if (!empty($Attachs)) {
					$s = Yii::app()->params->web_root;
					$i = strrpos($s, '/'); $a = strlen($s)-1;
					if ($i != $a)	$s.='/';
					foreach ($Attachs as $foto)
						@unlink ($s.$foto);
				}
			}
		}

		$this->pageTitle = 'Размещение объекта';
		$this->pageDescription = '';
		$this->pageKeywords = '';
		//Возьмём город из сессии
		$form->city=Yii::app()->user->getState('glcity');

		if ($wasSend)
			$this->render('success');
		else
			$this->render('view', array('form' =>$form, 'kind' =>$kind, 'about'=>$about));
	}

}?>

protected/views/sendorder/success.php
<div class="story">
	<p>Ваша заявка на размещение объекта принята.<br />В ближайшее время наш менеджер свяжется Вами для уточнения деталей.<br /><?php echo CHtml::link('Добавить еще', array('sendorder/view'));?> объекты?</p>
</div>

protected/views/sendorder/view.php
<script>
	$(function(){
        $('#SendOrder_city').attr('readonly', true);

        hide_popup();
        /*При клике на город заполняем значение инпута */
        $('.city_list li').click(function(){
            var city = $(this).text();
            $(this).parent().find('li').removeClass('active');
            $(this).addClass('active');
            $('#SendOrder_city').val(city);
            $('#Popup2Close').click();
        });

        function show_popup(){
            $('#Popup2').show();
            $('#Popup2').css('visibility', 'visible');
            $('#Popup2Fog').show();
        }
        function hide_popup(){
            $('#Popup2').hide();
            $('#Popup2Fog').hide();
        }

        $('#Popup2Close, #Popup2Fog').click(function(){
            hide_popup();
        });

        $('#SendOrder_city').click(function(){
            show_popup();
        });

    });
</script>


<h1 class="h101">Размещение объекта</h1>
<div class="desc01">
    Данная страница предназначена для быстрого размещения Ваших объектов и не требует регистрации на сайте. После размещения модератор сайта свяжется с Вами и уточнит необходимые детали. <?php if (Yii::app()->user->isGuest):?>Напоминаем, что <?php echo CHtml::link('регистрация', array('registration/view'), array('class'=>'link01'));?> позволит Вам пользоваться всем функционалом сайта.<?php endif;?><br />
    Подробнее о всех возможностях сайта Вы можете узнать на странице <a class="link01" href="/page/how_work.html">Как работает com-arenda</a>
</div>


<?php echo CHtml::form('', 'post', array('enctype'=>'multipart/form-data'));?>


<?php if($form->hasErrors()):?>
<div class="form01_grp">
    <div class="form01_blk">
        <div class="errorFormat02">
			<?php echo CHtml::errorSummary($form, 'Исправьте, пожалуйста, следующие ошибки:');?>
        </div>
    </div>
</div>
<?php endif;?>
<div class="form01_grp">
    <div class="form01_blk bFFF">
        <h1>Сдаю:</h1>
        <div class="m_0010b"><label class="bOffice checkbox02_lbl" onclick="checkboxBg(event);"><input class="checkbox01 m_0000_0030_0000_0000" name="SendOrder[kind]" type="radio" value="0"<?php echo ($kind==0)?' checked="checked"':'';?> />Офис
        </label><label class="bShop checkbox02_lbl" onclick="checkboxBg(event);"><input class="checkbox01 m_0000_0030_0000_0000" name="SendOrder[kind]" type="radio" value="1"<?php echo ($kind==1)?' checked="checked"':'';?> />Торговое помещение
        </label><label class="bEnterprise checkbox02_lbl" onclick="checkboxBg(event);"><input class="checkbox01 m_0000_0030_0000_0000" name="SendOrder[kind]" type="radio" value="2"<?php echo ($kind==2)?' checked="checked"':'';?> />Склад/Производство
        </label></div>
    </div><div class="note01">
    Выберите тип сдаваемого помещения
</div>
</div>
<div class="form01_grp">
    <div class="form01_blk">
        <h1>Основные характеристики помещения:</h1>
        <div>
            <div class="m_0015b">
                <div class="input01_lbl m_0015r">Город <?php echo CHtml::activeTextField($form, 'city', array('class'=>'input01 w90'));?> <b class="cB83939">*</b>
                </div>
                <div class="input01_lbl m_0015r">Район <?php echo CHtml::activeTextField($form, 'district', array('class'=>'input01 w90'));?> <b class="cB83939">*</b>
                </div>
                <div class="input01_lbl">Улица <?php echo CHtml::activeTextField($form, 'street', array('class'=>'input01 w90'));?> <b class="cB83939">*</b>
                </div>
            </div>
            <div class="m_0015b">
                <div class="input01_lbl m_0015r">Дом <?php echo CHtml::activeTextField($form, 'house', array('maxlength'=>4, 'class'=>'input01 w40'));?>
                </div>
                <div class="input01_lbl m_0015r">Этаж <?php echo CHtml::activeTextField($form, 'staging', array('maxlength'=>3, 'class'=>'input01 w30'));?>
                </div>
                <div class="input01_lbl m_0015r">Этажность <?php echo CHtml::activeTextField($form, 'stage', array('maxlength'=>3, 'class'=>'input01 w30'));?>
                </div>
                <div class="input01_lbl">Корпус/Строение <?php echo CHtml::activeTextField($form, 'housing', array('maxlength'=>7, 'class'=>'input01 w50'));?>
                </div>
            </div>
            <div class="m_0005b">
                <div class="input01_lbl m_0015r">Общая площадь помещения <?php echo CHtml::activeTextField($form, 'square', array('maxlength'=>6, 'class'=>'input01 w40'));?>
                </div>
                <div class="input01_lbl m_0015r">Арендная ставка (руб./м<sup>2</sup>) <?php echo CHtml::activeTextField($form, 'price', array('maxlength'=>8, 'class'=>'input01 w60'));?>
                </div>
            </div>
        </div>
    </div><div class="note01">
    Укажите параметры сдаваемого помещения.
</div>
</div>
<div class="form01_grp">
    <div class="form01_blk">
        <h1>Фотографии</h1>
        <div>
            <div class="fupload01 m_0015b" onmousedown="fakeUploadsDown(event);" onmouseup="fakeUploadsUp(event);" onmousemove="fakeUploadsMove(event);" onmouseout="fakeUploadsOut(event);"><?php echo CHtml::activeFileField($form, '[1]fotos', array('class'=>'upload01', 'size'=>'45'));?></div><br />
            <div class="fupload01 m_0015b" onmousedown="fakeUploadsDown(event);" onmouseup="fakeUploadsUp(event);" onmousemove="fakeUploadsMove(event);" onmouseout="fakeUploadsOut(event);"><?php echo CHtml::activeFileField($form, '[2]fotos', array('class'=>'upload01', 'size'=>'45'));?></div><br />
            <div class="fupload01 m_0015b" onmousedown="fakeUploadsDown(event);" onmouseup="fakeUploadsUp(event);" onmousemove="fakeUploadsMove(event);" onmouseout="fakeUploadsOut(event);"><?php echo CHtml::activeFileField($form, '[3]fotos', array('class'=>'upload01', 'size'=>'45'));?></div><br />
            <div class="fupload01 m_0015b" onmousedown="fakeUploadsDown(event);" onmouseup="fakeUploadsUp(event);" onmousemove="fakeUploadsMove(event);" onmouseout="fakeUploadsOut(event);"><?php echo CHtml::activeFileField($form, '[4]fotos', array('class'=>'upload01', 'size'=>'45'));?></div><br />
            <div class="fupload01 m_0015b" onmousedown="fakeUploadsDown(event);" onmouseup="fakeUploadsUp(event);" onmousemove="fakeUploadsMove(event);" onmouseout="fakeUploadsOut(event);"><?php echo CHtml::activeFileField($form, '[5]fotos', array('class'=>'upload01', 'size'=>'45'));?></div><br />
        </div>
        <h1>Дополнительно</h1>
        <div class="m_0005b"><?php echo CHtml::textArea('SendOrder[about]', $about, array('class'=>'h90 textarea01 w440'));?></div>
    </div>
    <div class="note01">
        Добавьте фотографии и описания вашему объекту.
    </div>
</div>
<div class="form01_grp">
    <div class="form01_blk">
        <h1>Контактная информация</h1>
        <div class="m_0015b">
            <div class="input01_lbl w130">Имя</div>
			<?php echo CHtml::activeTextField($form, 'name', array('class'=>'input01 w240', 'style'=>'vertical-align:middle;'));?> <b class="cB83939">*</b>
        </div>
        <div class="m_0015b">
            <div class="input01_lbl w130">Контактный телефон</div>
			<?php echo CHtml::activeTextField($form, 'phone', array('class'=>'input01 w240', 'style'=>'vertical-align:middle;'));?> <b class="cB83939">*</b>
        </div>
        <div class="m_0005b">
            <div class="input01_lbl w130">E-mail</div>
		<?php echo CHtml::activeTextField($form, 'e_mail', array('class'=>'input01 w240', 'style'=>'vertical-align:middle;'));?> <b class="cB83939">*</b>
        </div>
    </div>
    <div class="note01">
        Укажите контактные данные для связи с вами.
    </div>
</div>
<div class="form01_grp">
    <div class="m_0000_0245_0000_0002 w520">
        <h3 class="dl h301 m_0015_0000_0000_0000">Введите результат вычисления</h3>
        <div class="dl"><?php $this->widget('CCaptcha', array('buttonLabel' => ''));?></div>
        <div class="dl">
			<?php echo CHtml::activeTextField($form, 'verifyCode', array('maxlength'=>5, 'class'=>'input01 m_0015_0000_0000_0000 w60'));?><br/>
            <span><a class="captcha01_rfs" id="yt0" href="#">Обновить</a></span>
        </div>
        <!--  <input class="checkbox01 m0000000200000000" type="checkbox"/> -->
        <!--  <span class="checkbox_label02">Я ознакомился с правилами размещения объявлений</span> -->
		<?php echo CHtml::submitButton('Добавить', array('class'=>'button01 m_0010_0000_0000_0000'));?>
    </div>
</div>


<?php echo CHtml::endForm();?>