protected/controllers/AdminreclamebannersController.php
<?php class AdminreclamebannersController extends CController{

	public $defaultAction = 'view';
	public $layout = 'control';
	public $pageDescription;
	public $pageKeywords;

	public function actionView(){

		$this->pageTitle = 'Просмотр баннерных рекламных кампаний';
		$this->pageDescription = '';
		$this->pageKeywords = '';
		$usr = Yii::app()->user;

        # Определяем сортировку для запроса, если нет сортировки то сортируем по id обекта
        $order = '';
		if (isset($_GET['sort'])){
		  $order = $_GET['sort'];
		  if (isset($_GET['type'])) $order .= ' desc';
		}
		if (empty($order)) $order = 'id';

		$criteria = new CDbCriteria;
		$criteria->alias = 'B';
		$criteria->select = 'B.id, B.created, CASE B.isActive when 1 then "да" else "нет" END as isActive, B.name, B.width, B.height, CASE B.onMain when 1 then "да" else "нет" END as onMain, CASE B.onSearch when 1 then "да" else "нет" END as onSearch, CASE B.onAny when 1 then "да" else "нет" END as onAny, B.start, B.stop, B.qty, (Select COUNT(*) from reclame_banner_stat S where S.camp=B.id) as "totalQty"';
		$criteria->order = 'B.'.$order;

		$qty = ReclameBanner::model()->count($criteria);
		# Постраничная разбивка
		$pages = new CPagination($qty);
		$pages->pageSize = 20;
		$pages->applyLimit($criteria);
		# Получаем текущую страницу (нумерация начинается с 0, поэтому +1)
		$Cpage = $pages->getCurrentPage()+1;
		$Items = ReclameBanner::model()->findAll($criteria);
		$this->render('view', array(
			'form'		=>$form,
			'rows'		=>$Items,
			'pages'		=>$pages,
			'foundQty'	=>$qty,
			'Cpage'		=>$Cpage
			));
	}

	public function actionAdd() {
		$Row = new ReclameBanner();
		if (!empty($_POST['ReclameBanner'])){
			$Row->attributes = $_POST['ReclameBanner'];
			$dateStart = $Row->start;
			$dateStop = $Row->stop;
			$Row->start = $this->convertDate($Row->start);
			$Row->stop = $this->convertDate($Row->stop);
			$Row->filename = CUploadedFile::getInstance($Row,'filename');
			if($Row->validate()){
				if (!empty($Row->filename)) {
					$translit_obj = $this->widget('LoadFileName', array('in_text'=>$Row->filename->name, 'len'=>100));
					$translit = $translit_obj->out_text;
					$name = substr($translit, 0, strrpos($translit, '.'));
					$ext = substr($translit, strrpos($translit, '.'));
					$random = mt_rand(10000, 99999);
					$fullname = $name.'_'.$random.$ext;
					$Row->filename->saveAs('storage/images/banners/'.$fullname);
					$Row->filename = $fullname;
				}
				if ($Row->save(false))
					$this->redirect(array('adminreclamebanners/view'));
			} else {
				$Row->start = $dateStart;
				$Row->stop = $dateStop;
			}
		}
		$this->render('add', array('form' =>$Row));
	}

	public function actionEdit() {
		$get = $this->widget('GetChek', array('get_mass'=>$_GET));
		$oRow = ReclameBanner::model()->findByPK($get->id_out);
		if (empty($oRow))
			throw new CHttpException(404);
		if (!empty($_POST['ReclameBanner'])){
			$oRow->attributes = $_POST['ReclameBanner'];
			$oRow->start = $this->convertDate($oRow->start);
			$oRow->stop = $this->convertDate($oRow->stop);
			if($oRow->validate()){
				if ($oRow->save(false))
					$this->redirect(array('adminreclamebanners/view'));
			}
		}
		$this->render('edit', array('form' =>$oRow,
			'oName'		=>$oRow->name,
			'oWidth'	=>$oRow->width,
			'oHeight'	=>$oRow->height,
			'banName'	=>$oRow->filename,
			'oIsActive'	=>$oRow->isActive,
			'oOnMain'	=>$oRow->onMain,
			'oOnSearch'	=>$oRow->onSearch,
			'oOnAny'	=>$oRow->onAny,
			'oStart'	=>$oRow->start,
			'oStop'		=>$oRow->stop,
			'oQty'		=>$oRow->qty
		));
	}

	public function actionDelete() {
		$get = $this->widget('GetChek', array('get_mass'=>$_GET));
		$Row = ReclameBanner::model()->findByPK($get->id_out);
		if (empty($Row))
			throw new CHttpException(404);
		if (isset($_GET['flg'])){
			if ($Row->delete(false)) {
				$s = Yii::app()->params->web_root;
				$i = strrpos($s, '/'); $a = strlen($s)-1;
				if ($i != $a)	$s.='/';
				$s.='storage/images/banners/';
				@unlink ($s.$Row->filename);
				// Удаляем статистику показов Кампании
				$cmd = Yii::app()->db->createCommand('Delete from reclame_banner_stat where camp='.$get->id_out.';');
				$cmd->execute();
				$this->redirect(array('adminreclamebanners/view'));
			}
		}
		$this->render('delete', array('id' =>$get->id_out));
	}

	public function filters(){
	return array(
		array(
			'application.filters.AccessFilter',
			'role'=>'admin',
		)
	);
	}

	private function convertDate($dt){
		list ($d, $m, $y) = explode('.', $dt);
		return $y.'-'.$m.'-'.$d;
	}
}
?>

protected/views/adminreclamebanners/_row.php
<tr>
	<td><?php $get = $this->widget('DateFormat', array('kind'=>5,'dbDate'=>$obj->created)); echo $get->date;?></td>
	<td><?php echo $obj->name;?></td>
	<td><?php echo $obj->width.'x'.$obj->height;?></td>
	<td><?php echo $obj->onMain;?></td>
	<td><?php echo $obj->onSearch;?></td>
	<td><?php echo $obj->onAny;?></td>
	<td><?php echo $obj->isActive;?></td>
	<td><?php $get = $this->widget('DateFormat', array('kind'=>1,'dbDate'=>$obj->start)); echo $get->date;?></td>
	<td><?php $get = $this->widget('DateFormat', array('kind'=>1,'dbDate'=>$obj->stop)); echo $get->date;?></td>
	<td><?php echo $obj->qty;?></td>
	<td><?php echo $obj->totalQty;?></td>
	<td><?php echo CHtml::link('Р', array('adminreclamebanners/edit', 'id'=>$obj->id));?></td>
	<td><?php echo CHtml::link('У', array('adminreclamebanners/delete', 'id'=>$obj->id));?></td>
</tr>

protected/views/adminreclamebanners/add.php
<?php echo CHtml::cssFile(Yii::app()->baseUrl.'/css/form.css'); ?>
<style type="text/css">
	div.settings {display:inline-block;}
	div.settings {display:block;}
	div.settings {margin:20px;}
	div.settings input {display:inline;}
	div.settings label {display:block; margin-bottom:4px; font-size:14px;}
	div.settings label.chkbxSpan {display: inline; margin-bottom:5px; padding-left:5px;}
</style>
Добавление рекламной кампании [<?php echo CHtml::link('отмена', array('adminreclamebanners/view'));?>]
<div class="form">
  <?php echo CHtml::form('', 'post', array('enctype'=>'multipart/form-data')); ?>
	<?php echo CHtml::errorSummary($form, 'Исправьте, пожалуйста, следующие ошибки:'); ?>
<div class="row">
	<?php echo CHtml::activeLabel($form, 'name'); ?><br />
	<?php echo CHtml::activeTextField($form, 'name', array('size'=>100, 'maxlength'=>127));?>
</div>
<div class="row">
	<?php echo CHtml::activeLabel($form, 'width'); ?><br />
	<?php echo CHtml::activeTextField($form, 'width', array('size'=>7, 'maxlength'=>4));?>
</div>
<div class="row">
	<?php echo CHtml::activeLabel($form, 'height'); ?><br />
	<?php echo CHtml::activeTextField($form, 'height', array('size'=>7, 'maxlength'=>4));?>
</div>
<div class="row">
    <?php echo CHtml::activeLabel($form, 'filename'); ?><br />
    <?php echo CHtml::activeFileField($form, 'filename'); ?>
</div>
<fieldset title="Настройки">
<div class="settings">
	<div class="row">
		<?php echo CHtml::activeCheckBox($form, 'isActive').' '.CHtml::activeLabel($form, 'isActive', array('class'=>'chkbxSpan'));?>
	</div>
	<div class="row">
		<?php echo CHtml::activeCheckBox($form, 'onMain').' '.CHtml::activeLabel($form, 'onMain', array('class'=>'chkbxSpan'));?>
	</div>
	<div class="row">
		<?php echo CHtml::activeCheckBox($form, 'onSearch').' '.CHtml::activeLabel($form, 'onSearch', array('class'=>'chkbxSpan'));?>
	</div>
	<div class="row">
		<?php echo CHtml::activeCheckBox($form, 'onAny').' '.CHtml::activeLabel($form, 'onAny', array('class'=>'chkbxSpan'));?>
	</div>
	<div class="row">
		<?php echo CHtml::activeLabel($form, 'start'); ?><?php echo CHtml::activeTextField($form, 'start', array('size'=>10, 'maxlength'=>10));?>
	</div>
	<div class="row">
		<?php echo CHtml::activeLabel($form, 'stop'); ?><?php echo CHtml::activeTextField($form, 'stop', array('size'=>10, 'maxlength'=>10));?>
	</div>
	<div class="row">
		<?php echo CHtml::activeLabel($form, 'qty'); ?><?php echo CHtml::activeTextField($form, 'qty', array('size'=>10, 'maxlength'=>5));?>
	</div>
</div>
</fieldset>

<div class="row buttons">
	<?php echo CHtml::submitButton('Сохранить', array('id'=>"submit")); ?>
</div>
<?php echo CHtml::endForm(); ?>
</div><!--form-->

protected/views/adminreclamebanners/delete.php
Вы уверенны, что хотите удалить указанную Вами Рекламную кампанию?<br /><br />
<?php echo CHtml::link('Да', array('adminreclamebanners/delete', 'id'=>$id, 'flg'=>'chek')); ?> <?php echo CHtml::link('Нет', array('adminreclamebanners/view')); ?>

protected/views/adminreclamebanners/edit.php
<?php echo CHtml::cssFile(Yii::app()->baseUrl.'/css/form.css'); ?>
<style type="text/css">
	div.settings {display:inline-block;}
	div.settings {display:block;}
	div.settings {margin:20px;}
	div.settings input {display:inline;}
	div.settings label {display:block; margin-bottom:4px; font-size:14px;}
	div.settings label.chkbxSpan {display: inline; margin-bottom:5px; padding-left:5px;}
</style>
Редактирование рекламной кампании [<?php echo CHtml::link('отмена', array('adminreclamebanners/view'));?>]
<div class="form">
	<?php echo CHtml::form();?>
	<?php echo CHtml::errorSummary($form, 'Исправьте, пожалуйста, следующие ошибки:'); ?>
<div class="row">
	<?php echo CHtml::activeLabel($form, 'name'); ?><br />
	<?php echo CHtml::activeTextField($form, 'name', array('value'=>$oName, 'size'=>100, 'maxlength'=>127));?>
</div>
<div class="row">
	<?php echo CHtml::activeLabel($form, 'width'); ?><br />
	<?php echo CHtml::activeTextField($form, 'width', array('value'=>$oWidth, 'size'=>7, 'maxlength'=>4));?>
</div>
<div class="row">
	<?php echo CHtml::activeLabel($form, 'height'); ?><br />
	<?php echo CHtml::activeTextField($form, 'height', array('value'=>$oHeight, 'size'=>7, 'maxlength'=>4));?>
</div>
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://active.macromedia.com/flash4/cabs/swflash.cab#version=4,0,0,0" width="<?php echo $oWidth;?>" height="<?php echo $oHeight;?>">
	<param name="movie" value="storage/images/banners/<?php echo $banName;?>">
	<param name="play" value="true">
	<param name="loop" value="true">
	<param name="quality" value="high">
	<embed src="storage/images/banners/<?php echo $banName;?>" play="true" loop="true" quality="high" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" width="<?php echo $oWidth;?>" height="<?php echo $oHeight;?>"></embed>
</object><br /><br />
<fieldset title="Настройки">
<div class="settings">
	<div class="row">
		<?php if ($oIsActive=='' || $oIsActive=='0') $cba = array(); else $cba = array('checked'=>'checked'); echo CHtml::activeCheckBox($form, 'isActive', $cba).' '.CHtml::activeLabel($form, 'isActive', array('class'=>'chkbxSpan')); ?>
	</div>
	<div class="row">
		<?php if ($oOnMain=='' || $oOnMain=='0') $cba = array(); else $cba = array('checked'=>'checked'); echo CHtml::activeCheckBox($form, 'onMain', $cba).' '.CHtml::activeLabel($form, 'onMain', array('class'=>'chkbxSpan')); ?>
	</div>
	<div class="row">
		<?php if ($oOnSearch=='' || $oOnSearch=='0') $cba = array(); else $cba = array('checked'=>'checked'); echo CHtml::activeCheckBox($form, 'onSearch', $cba).' '.CHtml::activeLabel($form, 'onSearch', array('class'=>'chkbxSpan')); ?>
	</div>
	<div class="row">
		<?php if ($oOnAny=='' || $oOnAny=='0') $cba = array(); else $cba = array('checked'=>'checked'); echo CHtml::activeCheckBox($form, 'onAny', $cba).' '.CHtml::activeLabel($form, 'onAny', array('class'=>'chkbxSpan')); ?>
	</div>
	<div class="row">
		<?php echo CHtml::activeLabel($form, 'start'); ?><?php $get = $this->widget('DateFormat', array('kind'=>1,'dbDate'=>$oStart)); echo CHtml::activeTextField($form, 'start', array('value'=>$get->date, 'size'=>10, 'maxlength'=>10)); ?>
	</div>
	<div class="row">
		<?php echo CHtml::activeLabel($form, 'stop'); ?><?php $get = $this->widget('DateFormat', array('kind'=>1,'dbDate'=>$oStop)); echo CHtml::activeTextField($form, 'stop', array('value'=>$get->date, 'size'=>10, 'maxlength'=>10)); ?>
	</div>
	<div class="row">
		<?php echo CHtml::activeLabel($form, 'qty'); ?><?php echo CHtml::activeTextField($form, 'qty', array('value'=>$oQty, 'size'=>10, 'maxlength'=>5)); ?>
	</div>
</div>
</fieldset>

<div class="row buttons">
	<?php echo CHtml::submitButton('Сохранить', array('id'=>"submit")); ?>
	<?php echo CHtml::resetButton('Сброс', array('id'=>'reset')); ?>
</div>
<?php echo CHtml::endForm(); ?>
</div><!--form-->

protected/views/adminreclamebanners/view.php
<?php echo CHtml::cssFile(Yii::app()->baseUrl.'/css/form.css'); ?>
<?php if (is_array($rows)):?>
Всего <?php echo $foundQty; ?> кампаний<br />
<?php echo CHtml::link('Добавить новую кампанию', array('adminreclamebanners/add')); ?><br /><br />
<?php if (!empty($rows)):?>
<style type="text/css">
table.sample {
  border-spacing: 2px;
  border-collapse: collapse;
  width: 100%;
  text-align: left;
}
table.sample th {
  border: 1px solid #000000;
  padding: 5px;
  background-color: #aaaaaa;
  text-align: center;
}
table.sample td {
  border: 1px solid #000000;
  padding: 5px;
}
table.sample td.action {
  text-align: center;
}
</style>
<?php echo CHtml::link('Сбросить сортировку', array('adminreclamebanners/view', 'page'=>$Cpage)); ?>
<table class="sample">
	<tr>
		<th rowspan="2">Создан <?php echo CHtml::link('&uarr;', array('adminreclamebanners/view', 'page'=>$Cpage, 'sort'=>'created')); ?>&nbsp;<?php echo CHtml::link('&darr;', array('adminreclamebanners/view', 'page'=>$Cpage, 'sort'=>'created', 'type'=>'desc')); ?>
		</th>
		<th rowspan="2">Имя кампании</th>
		<th rowspan="2">Размеры (Ш х В)</th>
		<th rowspan="2">Глав</th>
		<th rowspan="2">Пск</th>
		<th rowspan="2">Друг</th>
		<th rowspan="2">Актив</th>
		<th colspan="2">Даты кампании</th>
		<th colspan="2">Показывать</th>
		<th rowspan="2">Р</th>
		<th rowspan="2">У</th>
	</tr>
	<tr>
		<th>старт <?php echo CHtml::link('&uarr;', array('adminreclamebanners/view', 'page'=>$Cpage, 'sort'=>'start')); ?>&nbsp;<?php echo CHtml::link('&darr;', array('adminreclamebanners/view', 'page'=>$Cpage, 'sort'=>'start', 'type'=>'desc')); ?>
		</th>
		<th>финиш <?php echo CHtml::link('&uarr;', array('adminreclamebanners/view', 'page'=>$Cpage, 'sort'=>'stop')); ?>&nbsp;<?php echo CHtml::link('&darr;', array('adminreclamebanners/view', 'page'=>$Cpage, 'sort'=>'stop', 'type'=>'desc')); ?>
		</th>
		<th>надо</th>
		<th>уже</th>
	</tr>
<?php
	foreach ($rows as $row)
		$this->renderPartial('_row', array('obj' =>$row));
?>
<?php endif; ?>
</table>
<div align="center">
<?php
  $this->widget('CLinkPager',array(
		'pages'          =>$pages,
		'maxButtonCount' =>5, # максимальное колличество вкладок на странице
		'header'         =>'<b>Перейти к странице:</b><br>', # заголовок
		'nextPageLabel'  =>'Вперед&gt;', # название кнопок навигаций next и prev
		'prevPageLabel'  =>'&lt;Назад',
  ));
?>
</div>
<i>Примечание</i>: При проверке кампании на ограничение по датам и кол-ву показов применяется <b>строгое</b> неравенство. Иными словами, если указана дата начала кампании 1 июня, то показы начнутся со 2-го июня. Если указана дата окончания 4 июня, то последним днем показов будет 3-е июня.<br />
<?php endif; ?>